In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
# df = pd.read_csv("/media/anubhav/New Volume/vidhaan/data_gen/Case-2022-08-26 (1).csv")
df = pd.read_csv("F:/vidhaan/advocate_performance/dataset_advocate_performance.csv")

In [3]:
del df['Unnamed: 0'],df['id']

In [4]:
del df['age']

In [5]:
del df['active cases']

In [6]:
df['case_type'] = df['speciality']

In [7]:
del df['speciality']

In [8]:
df.head()

,name,experience (yrs),fees,avg resolve time (days),case_type
0,misri,15.0,156290,618,Petition for Special Leave to Appeal
1,tina,30.0,307280,598,Original Suit
2,dharmendera,14.0,145938,577,Contempt Petition (Civil)
3,sukh,10.0,105270,494,Arbitration Petition
4,mairy,12.0,125168,566,Transferred Case Petition

In [9]:
del df['experience (yrs)'],df['avg resolve time (days)']

In [10]:
df['state'] = np.nan
df['court'] = np.nan
df['petitioner'] = np.nan
df['respondent'] = 'University Grants Commission'
df['case_stage'] = np.nan

In [11]:
df.head()

,name,fees,case_type,state,court,petitioner,respondent,case_stage
0,misri,156290,Petition for Special Leave to Appeal,NaN,NaN,NaN,University Grants Commission,NaN
1,tina,307280,Original Suit,NaN,NaN,NaN,University Grants Commission,NaN
2,dharmendera,145938,Contempt Petition (Civil),NaN,NaN,NaN,University Grants Commission,NaN
3,sukh,105270,Arbitration Petition,NaN,NaN,NaN,University Grants Commission,NaN
4,mairy,125168,Transferred Case Petition,NaN,NaN,NaN,University Grants Commission,NaN

In [12]:
df.drop([0,1,2,3])

,name,fees,case_type,state,court,petitioner,respondent,case_stage
4,mairy,125168,Transferred Case Petition,NaN,NaN,NaN,University Grants Commission,NaN
5,sube,276080,Contempt Petition (Criminal),NaN,NaN,NaN,University Grants Commission,NaN
6,mangala,347244,Criminal Appeal Petition,NaN,NaN,NaN,University Grants Commission,NaN
7,soona,235322,Contempt Petition (Civil),NaN,NaN,NaN,University Grants Commission,NaN
8,bhemji,316519,Transferred Case Petition,NaN,NaN,NaN,University Grants Commission,NaN
...,...,...,...,...,...,...,...,...
6481,sahbaj,365792,Arbitration Petition,NaN,NaN,NaN,University Grants Commission,NaN
6482,davendra,156170,Original Suit,NaN,NaN,NaN,University Grants Commission,NaN
6483,marzina,206280,Writ Petition,NaN,NaN,NaN,University Grants Commission,NaN
6484,bulet,336518,Transferred Case Petition,NaN,NaN,NaN,University Grants Commission,NaN
6485,nizamuddin,145798,Arbitration Petition,NaN,NaN,NaN,University Grants Commission,NaN

In [13]:
types_of_cases = ["Civil (Appeal) Petition","Contempt Petition (Civil)","Writ Petition"]

In [14]:
types_of_court = ['Supreme Court','High Court','District Court','Lower Court']

In [15]:
stage_of_cases = ['Ongoing','Disposed']

In [16]:
states = ["Andhra Pradesh","Arunachal Pradesh" ,"Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman and Nicobar Islands","Chandigarh","Dadra and Nagar Haveli","Daman and Diu","Lakshadweep","Delhi","Puducherry"]

In [17]:
# states = ['Chhattisgarh','Rajasthan','Punjab','Uttar Pradesh','Haryana','Delhi','Karnataka','Tamil Nadu','Maharashtra','Madhya Pradesh','Gujrat','Telangana']

In [18]:
d = pd.DataFrame()

In [19]:
for i in range(len(df)):
    df['state'][i] = random.choice(states)
    df['court'][i] = random.choice(types_of_court)
    df['case_stage'][i] = random.choice(stage_of_cases)

C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/2630004742.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['state'][i] = random.choice(states)
C:\Users\AK-47\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/2630004742.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['court'][i] = random.choice(types_of_court)
C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/2630004742.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['case_stage'][i] = random.choice(stage_of_cases)

In [20]:
df['coram'] = df['fees']

In [21]:
del df['fees']

In [22]:
df['coram'] = (df['coram']*2).astype(int)

In [23]:
df.head()

,name,case_type,state,court,petitioner,respondent,case_stage,coram
0,misri,Petition for Special Leave to Appeal,Chandigarh,Lower Court,NaN,University Grants Commission,Disposed,312580
1,tina,Original Suit,Puducherry,High Court,NaN,University Grants Commission,Ongoing,614560
2,dharmendera,Contempt Petition (Civil),Goa,District Court,NaN,University Grants Commission,Ongoing,291876
3,sukh,Arbitration Petition,Delhi,High Court,NaN,University Grants Commission,Ongoing,210540
4,mairy,Transferred Case Petition,Jammu and Kashmir,Supreme Court,NaN,University Grants Commission,Disposed,250336

In [24]:
df['bench'] = np.nan

In [25]:
for i in range(len(df)):
    df['bench'][i] = random.choice(['Single bench','Single bench','Single bench','Two judge bench'])

C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/1256552179.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bench'][i] = random.choice(['Single bench','Single bench','Single bench','Two judge bench'])
C:\Users\AK-47\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [26]:
df.head()

,name,case_type,state,court,petitioner,respondent,case_stage,coram,bench
0,misri,Petition for Special Leave to Appeal,Chandigarh,Lower Court,NaN,University Grants Commission,Disposed,312580,Single bench
1,tina,Original Suit,Puducherry,High Court,NaN,University Grants Commission,Ongoing,614560,Single bench
2,dharmendera,Contempt Petition (Civil),Goa,District Court,NaN,University Grants Commission,Ongoing,291876,Single bench
3,sukh,Arbitration Petition,Delhi,High Court,NaN,University Grants Commission,Ongoing,210540,Two judge bench
4,mairy,Transferred Case Petition,Jammu and Kashmir,Supreme Court,NaN,University Grants Commission,Disposed,250336,Single bench

In [27]:
df['case_name'] = np.nan

In [28]:
for i in range(len(df)):
    df['case_name'][i] = str(df['name'][i])+' vs '+str(df['respondent'][i])

C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/2804731140.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['case_name'][i] = str(df['name'][i])+' vs '+str(df['respondent'][i])
C:\Users\AK-47\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [29]:
df.head()

,name,case_type,state,court,petitioner,respondent,case_stage,coram,bench,case_name
0,misri,Petition for Special Leave to Appeal,Chandigarh,Lower Court,NaN,University Grants Commission,Disposed,312580,Single bench,misri vs University Grants Commission
1,tina,Original Suit,Puducherry,High Court,NaN,University Grants Commission,Ongoing,614560,Single bench,tina vs University Grants Commission
2,dharmendera,Contempt Petition (Civil),Goa,District Court,NaN,University Grants Commission,Ongoing,291876,Single bench,dharmendera vs University Grants Commission
3,sukh,Arbitration Petition,Delhi,High Court,NaN,University Grants Commission,Ongoing,210540,Two judge bench,sukh vs University Grants Commission
4,mairy,Transferred Case Petition,Jammu and Kashmir,Supreme Court,NaN,University Grants Commission,Disposed,250336,Single bench,mairy vs University Grants Commission

In [30]:
df['petitioner'] = df['name']

In [31]:
del df['name']

In [32]:
df.head()

,case_type,state,court,petitioner,respondent,case_stage,coram,bench,case_name
0,Petition for Special Leave to Appeal,Chandigarh,Lower Court,misri,University Grants Commission,Disposed,312580,Single bench,misri vs University Grants Commission
1,Original Suit,Puducherry,High Court,tina,University Grants Commission,Ongoing,614560,Single bench,tina vs University Grants Commission
2,Contempt Petition (Civil),Goa,District Court,dharmendera,University Grants Commission,Ongoing,291876,Single bench,dharmendera vs University Grants Commission
3,Arbitration Petition,Delhi,High Court,sukh,University Grants Commission,Ongoing,210540,Two judge bench,sukh vs University Grants Commission
4,Transferred Case Petition,Jammu and Kashmir,Supreme Court,mairy,University Grants Commission,Disposed,250336,Single bench,mairy vs University Grants Commission

In [33]:
df['case_filling_year'] = np.nan

In [34]:
for i in range(len(df)):
    df['case_filling_year'][i] = int(np.random.randint(low=2011,high=2020))

C:\Users\AK-47\AppData\Local\Temp/ipykernel_13068/2812179737.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['case_filling_year'][i] = int(np.random.randint(low=2011,high=2020))

In [35]:
df['case_filling_year'] = df['case_filling_year'].astype(int)

In [36]:
df.head()

,case_type,state,court,petitioner,respondent,case_stage,coram,bench,case_name,case_filling_year
0,Petition for Special Leave to Appeal,Chandigarh,Lower Court,misri,University Grants Commission,Disposed,312580,Single bench,misri vs University Grants Commission,2016
1,Original Suit,Puducherry,High Court,tina,University Grants Commission,Ongoing,614560,Single bench,tina vs University Grants Commission,2013
2,Contempt Petition (Civil),Goa,District Court,dharmendera,University Grants Commission,Ongoing,291876,Single bench,dharmendera vs University Grants Commission,2013
3,Arbitration Petition,Delhi,High Court,sukh,University Grants Commission,Ongoing,210540,Two judge bench,sukh vs University Grants Commission,2013
4,Transferred Case Petition,Jammu and Kashmir,Supreme Court,mairy,University Grants Commission,Disposed,250336,Single bench,mairy vs University Grants Commission,2016

In [37]:
df.to_json("F:/vidhaan/data_gen/data.json",orient='records')

In [38]:
df.head()

,case_type,state,court,petitioner,respondent,case_stage,coram,bench,case_name,case_filling_year
0,Petition for Special Leave to Appeal,Chandigarh,Lower Court,misri,University Grants Commission,Disposed,312580,Single bench,misri vs University Grants Commission,2016
1,Original Suit,Puducherry,High Court,tina,University Grants Commission,Ongoing,614560,Single bench,tina vs University Grants Commission,2013
2,Contempt Petition (Civil),Goa,District Court,dharmendera,University Grants Commission,Ongoing,291876,Single bench,dharmendera vs University Grants Commission,2013
3,Arbitration Petition,Delhi,High Court,sukh,University Grants Commission,Ongoing,210540,Two judge bench,sukh vs University Grants Commission,2013
4,Transferred Case Petition,Jammu and Kashmir,Supreme Court,mairy,University Grants Commission,Disposed,250336,Single bench,mairy vs University Grants Commission,2016

In [39]:
dm = df[df['state']=='Tamil Nadu']

In [40]:
dm.head()

,case_type,state,court,petitioner,respondent,case_stage,coram,bench,case_name,case_filling_year
22,Contempt Petition (Civil),Tamil Nadu,District Court,atish,University Grants Commission,Ongoing,410040,Single bench,atish vs University Grants Commission,2017
78,Election Petition,Tamil Nadu,Lower Court,sarvjeet,University Grants Commission,Disposed,333008,Two judge bench,sarvjeet vs University Grants Commission,2016
183,Writ Petition,Tamil Nadu,Supreme Court,viccky,University Grants Commission,Ongoing,171360,Single bench,viccky vs University Grants Commission,2011
310,Arbitration Petition,Tamil Nadu,Supreme Court,gulwasha,University Grants Commission,Ongoing,613300,Two judge bench,gulwasha vs University Grants Commission,2014
321,Writ Petition,Tamil Nadu,District Court,ravinath,University Grants Commission,Disposed,730576,Single bench,ravinath vs University Grants Commission,2018

In [41]:
len(dm)

185

In [42]:
class my_dictionary(dict):
 
  # __init__ function
    def __init__(self):
        self = dict()
 
  # Function to add key:value
    def add(self, key, value):
        self[key] = value

In [43]:
dict_obj = my_dictionary()

In [44]:
for i in states:
    dict_obj.add(i,len(df[df['state']==i]))

In [45]:
print(dict_obj)

{'Andhra Pradesh': 176, 'Arunachal Pradesh': 181, 'Assam': 183, 'Bihar': 174, 'Chhattisgarh': 177, 'Goa': 171, 'Gujarat': 183, 'Haryana': 169, 'Himachal Pradesh': 162, 'Jammu and Kashmir': 149, 'Jharkhand': 190, 'Karnataka': 173, 'Kerala': 169, 'Madhya Pradesh': 184, 'Maharashtra': 151, 'Manipur': 194, 'Meghalaya': 152, 'Mizoram': 186, 'Nagaland': 174, 'Odisha': 188, 'Punjab': 181, 'Rajasthan': 203, 'Sikkim': 187, 'Tamil Nadu': 185, 'Telangana': 200, 'Tripura': 183, 'Uttar Pradesh': 226, 'Uttarakhand': 148, 'West Bengal': 162, 'Andaman and Nicobar Islands': 199, 'Chandigarh': 187, 'Dadra and Nagar Haveli': 164, 'Daman and Diu': 231, 'Lakshadweep': 180, 'Delhi': 183, 'Puducherry': 181}